# config/packages/nelmio_api_doc.yaml
nelmio_api_doc:
    documentation:
        info:
            title: 'Projet CRM Doc'
            description: 'Projet CIR 2, CRM'
            version: '1.0.0'
    areas:
        default:
            path_patterns: [ ^/api ]
