<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250512054504 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql(<<<'SQL'
            CREATE TABLE opportunity (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, job_title VARCHAR(255) NOT NULL, company VARCHAR(255) NOT NULL, contract_type VARCHAR(255) NOT NULL, location VARCHAR(255) NOT NULL, salary_min DOUBLE PRECISION NOT NULL, salary_max DOUBLE PRECISION NOT NULL, salary_currency VARCHAR(255) NOT NULL, status VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE recruiter DROP created_at
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE recruiter DROP updated_at
        SQL);
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql(<<<'SQL'
            DROP TABLE opportunity
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE recruiter ADD created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE recruiter ADD updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL
        SQL);
    }
}
